import "../../style/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";

import { Providers } from "@/app/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto wallet",
  description: "Generated by Chunlin Wang",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
        <html lang="en" className="h-full">
          <body className={`${inter.className} h-full`}>
            <Providers>{props.children}</Providers>
          </body>
        </html>
  );
}
